import { useEffect } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Sparkles } from 'lucide-react'
import ToolCard from '../components/ToolCard'
import SummarizerTool from '../components/tools/SummarizerTool'
import QuizTool from '../components/tools/QuizTool'
import PlannerTool from '../components/tools/PlannerTool'
import AssistantTool from '../components/tools/AssistantTool'

const toolTitles = {
  summarizer: 'Notes Summarizer',
  quiz: 'Quiz Generator',
  planner: 'Study Planner',
  assistant: 'AI Study Assistant',
}

export default function Tools() {
  const [searchParams] = useSearchParams()

  const paramTool = searchParams.get('tool')
  const activeTool = paramTool && toolTitles[paramTool] ? paramTool : 'summarizer'

  useEffect(() => {
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }, [activeTool])

  const tools = ['summarizer', 'quiz', 'planner', 'assistant']

  return (
    <div className="bg-slate-50 dark:bg-slate-900">
      <section className="border-b border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-900">
        <div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8">
          <span className="badge bg-primary-100 text-primary-700 dark:bg-primary-500/15 dark:text-primary-300">
            <Sparkles className="h-3.5 w-3.5" />
            AI Tools
          </span>
          <h1 className="mt-3 text-3xl font-bold tracking-tight text-slate-900 dark:text-white sm:text-4xl">
            Your study workspace
          </h1>
          <p className="mt-3 max-w-2xl text-slate-500 dark:text-slate-400">
            Pick a tool to get started. Study chat, summaries, and quizzes are generated by AI
            through a secure backend, while your tasks and chat history stay on your device.
          </p>
        </div>
      </section>

      <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
        <div className="grid gap-8 lg:grid-cols-[280px_1fr]">
          {/* Tool sidebar */}
          <aside className="lg:sticky lg:top-24 lg:self-start">
            <div className="space-y-3">
              {tools.map((toolId) => (
                <ToolCard key={toolId} toolId={toolId} active={activeTool === toolId} />
              ))}
            </div>
            <div className="mt-4 rounded-xl border border-primary-100 bg-primary-50 p-4 text-xs leading-relaxed text-primary-800 dark:border-primary-500/30 dark:bg-primary-500/10 dark:text-primary-200">
              <strong className="font-semibold">Good to know:</strong> Tasks and chat history are stored
              locally in your browser's storage. AI requests are sent to the StudyMate backend —
              never your API keys.
            </div>
          </aside>

          {/* Active tool */}
          <main className="min-w-0">
            <div key={activeTool} className="animate-fade-in">
              {activeTool === 'summarizer' && <SummarizerTool />}
              {activeTool === 'quiz' && <QuizTool />}
              {activeTool === 'planner' && <PlannerTool />}
              {activeTool === 'assistant' && <AssistantTool />}
            </div>
          </main>
        </div>
      </div>
    </div>
  )
}